# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Qasim Asghar
email: me@qasimasghar.com
description: | # this means to ignore newlines until "baseurl:"
  I'm Qasim Asghar, a software developer based in Ipswich.
  
  This is my thought dumping ground. Filled with blog posts about something random I've tried over the weekend or information about some of my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://qasimasghar.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: qasimaasghar
github_username:  qasimasghar

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-66637550-1